version: '3'

networks:
  presenter:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    tty: true
    restart: unless-stopped
    container_name: presenter-app
    working_dir: /var/www
    volumes:
      - ../.:/var/www
    depends_on:
      - db
    env_file:
      - ../.env
    networks:
      - presenter

  nginx:
    image: 'nginx:alpine'
    container_name: presenter-nginx
    restart: unless-stopped
    tty: true
    ports:
      - '8001:80'
      - '443:443'
    volumes:
      - ../.:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db
    networks:
      - presenter

  db:
    image: mariadb
    container_name: presenter-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: presenter
      MYSQL_DATABASE: presenter
      MYSQL_USER: presenter
      MYSQL_PASSWORD: presenter
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - presenter

#  redis:
#    image: redis:6.0-buster
#    container_name: presenter-redis
#    ports:
#      - "6379:6379"
#    networks:
#      - presenter
